### ISSUE TITLE
Any possibility of arm64/v8 support?

### ISSUE THREAD

**Issue by Dukewill** [gqbre/docker-rclone-proxy#2]
Hi there and thanks a ton for your fantastic modification!
I've evaluated several rclone-mount dockers but none of them support arm64/v8 architecture.
Is it possible for you to implement one?

#

**Comment by Dukewill** [comment]
#

**Comment by Dukewill** [comment]
Ref. https://github.com/Mumie-hub/docker-services/pull/44#issue-640092326

**Comment by gqbre** [comment]
@Dukewill Sorry for missed the Issue, just test with amd64. You can try arm64 architecture now, welcome ro pull requests.
